services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - 3307:3306
    environment:
        MYSQL_DATABASE: users_database
        MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  backend:
    build: ./springboot2-jpa-crud-example  # This should point to your backend project folder
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - app-network

  frontend:
    build: ./angular8-springboot-client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: